name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pester:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -RequiredVersion 4.10.1 -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Run tests
        shell: pwsh
        run: |
          $result = Invoke-Pester './Clean-NuGetPackages.Tests.ps1' -PassThru
          if ($result.FailedCount -gt 0) { exit 1 }
